allowBuilds:
  sharp: false
ignoredBuiltDependencies:
  - sharp
minimumReleaseAgeExclude:
  - postcss@8.5.10
  - sanitize-html@2.17.4
overrides:
  postcss@<8.5.10: ^8.5.10
  sanitize-html@<=2.17.3: ^2.17.4
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  yaml@>=2.0.0 <2.8.3: 2.8.3
  next@>=16.0.0-beta.0 <16.2.3: ">=16.2.3"
  sanitize-html@>=2.17.2 <2.17.3: ">=2.17.3"
  next@>=16.0.0 <16.2.5: ">=16.2.5"
  next@>=16.0.0 <16.2.6: ">=16.2.6"
